application:
  Name: collection-center
api:
  ListenPort: 8080
  Debug: true
  LogLevel: debug
  Secret: $%^$Secret@#as{?.
  SystemEmail: info@orca.email.cn
  QueuePrefetchLimit: 100
  Origin: http://127.0.0.1
  JwtSecret: 9527
database:
  DSN: "postgres://orca_web3:orca_web3!@192.168.8.63:5444/collection_center?sslmode=disable"
  ReadDSN: []
  Active: 20
  Idle: 200
  ShowSql: true
  IdleTimeout: "300s"
  QueryTimeout: "1s"
  ExecTimeout: "1s"
  TranTimeout: "1s"
redis:
  Addr: "192.168.8.63:6379"
  #  Addr: "192.168.124.116:6379"
  Auth: "orca_redis"
  Db: 11 # 个人开发可以错开使用, 取值范围 0-15
  DialTimeout: "1s"
  ReadTimeout: "200ms"
  WriteTimeout: "200ms"
log:
  LogPath: ""
email:
  Host: "smtp.gmail.com"
  Port: 465
  User: "orcayihaoji@gmail.com"
  Pass: "ifgmqpidheqgpctm"

#################
# web3 配置项
rpc:
  test: true
  ethRpc:
    - https://eth-goerli.g.alchemy.com/v2/ALmhXu_g7MrNqg9bB5TSZj0Ocxv6X0Iq
    - https://eth-goerli.g.alchemy.com/v2/Vo7tbYU-XxlEwjpIVfzNYMndZGTIfE9V
  ethMaxGasPrice: 50000000000 # 50Gwei 用于子钱包到主钱包的转账 GasPrice 限制
  btcRpc:
    # btcRpc不要填入 https:// 前缀
    test:
      - go.getblock.io/10aacc88908d47b89997b8f72a180757
    mainnet:
      - go.getblock.io/0bdcdc1ae4d34e41aebeb1089a821706
## oss 调用地址
#oss:
#  AccessKeyId : "a"
#  AccessKeySecret : "a"
#  EndPoint : "https://a.aliyuncs.com"
#  CommonBucket : "a"
#  RoleArn : "acs:ram::11111:role/gt-medium-oss-uat"
#  RoleSessionName : "a"
hystrix:
  timeout: 1000
  maxConcurrentRequests: 100
  requestVolumeThreshold: 1000
  sleepWindow: 5000
  errorPercentThreshold: 50