package ecode

var CM = map[int]map[string]string{
	0:    {"EN": "OK", "CN": "OK"},
	-304: {"EN": "NO CHANGE", "CN": "没有改动"},
	-307: {"EN": "redirect", "CN": "装车跳转"},
	-400: {"EN": "wrong request", "CN": "请求错误"},
	-401: {"EN": "not authorized", "CN": "未认证"},
	-403: {"EN": "permission denied", "CN": "访问权限不足"},
	-404: {"EN": "no data", "CN": "啥都木有"},
	-405: {"EN": "invalid method", "CN": "不支持该方法"},
	-409: {"EN": "conflict request", "CN": "冲突"},
	-498: {"EN": "client stop", "CN": "客户端取消请求"},
	-500: {"EN": "server error", "CN": "服务器错误"},
	-503: {"EN": "server overload", "CN": "过载保护,服务暂不可用"},
	-504: {"EN": "service out time", "CN": "服务调用超时"},
	-509: {"EN": "out of boundary", "CN": "超出限制"},

	10001: {"EN": "illegal param", "CN": "参数错误"},
	10101: {"EN": "email is exist", "CN": "邮箱被占用"},
	10102: {"EN": "verify code invalid", "CN": "验证码无效"},
	10103: {"EN": "email and password not match", "CN": "邮箱密码不匹配"},
	10104: {"EN": "no login", "CN": "账号未登录"},
	10105: {"EN": "collect info and collect address not match", "CN": "收款信息和收款地址不匹配"},
	10106: {"EN": "token symbol not exist", "CN": "代币不存在"},
	10107: {"EN": "email is not exist", "CN": "邮箱不存在"},
	10108: {"EN": "USDT rate can not change", "CN": "USDT汇率不能修改"},
	10109: {"EN": "rate must be > 0", "CN": "设置汇率必须大于0"},
	10110: {"EN": "collect wallet address format error", "CN": "收款地址格式错误"},
	10111: {"EN": "create project failed", "CN": "创建项目失败"},
	10112: {"EN": "check token address error", "CN": "检查Token地址错误"},
	10113: {"EN": "add token info failed", "CN": "添加Token信息失败"},
	10114: {"EN": "project not exist", "CN": "项目不存在"},
	10115: {"EN": "no project permission", "CN": "没有项目权限"},
	10116: {"EN": "update project info failed", "CN": "更新项目信息失败"},
	10117: {"EN": "update collect address failed", "CN": "更新收款地址失败"},
	10118: {"EN": "update collect rate failed", "CN": "更新汇率失败"},
	10119: {"EN": "freeze project failed", "CN": "冻结项目失败"},

	10207: {"EN": "request frequency too high", "CN": "请求发送频率过高"},
}
